### ISSUE TITLE
Error when trying to run a request

### ISSUE THREAD

**Issue by rolltidega** [veracode/veracode-postman#2]
I am getting an error trying to run the pre-request script:

There was an error in evaluating the Pre-request Script:TypeError: Cannot read properties of undefined (reading 'split')

I have the api_key and api_key variables defined properly so I am not sure what I need to do.

I have some testing I want to do using Postman.

**Comment by flamur85** [comment]
I had the same issue. Try updating Postman to the newest version and try again. Also verify that the environment variables are of 'Secret' type and that your in the new environment (look at the drop down in the top right of Postman and select the environment you created for Veracode).

**Comment by btanand** [comment]
I see the same issue. I ensured that the variable types are secret and I am using Postman v10. The pre requisite script should have condition to  check if split is present in the first place.

**Comment by relaxnow** [comment]
Thank you for your help @flamur85 !
I agree with @btanand , there should be a null check after https://github.com/veracode/veracode-postman/blob/main/pre-request.js#L6-L7 so that if the variables are not available we give a decent error message.
